### PR TITLE
V1.4.2.2

### PR DESCRIPTION
**Pull request by ColinDKelley**

### CODE REVIEW

**Comment by ColinDKelley** [comment]
:+1:

**Comment by peterwilson** [comment]
:+1:

**Comment by ColinDKelley** [comment]
@leekirchhoff  Has this already been merged elsewhere? Should I close out this PR?

**Comment by leekirchhoff** [comment]
This PR can be closed. We are not merging it anywhere. v1.4.2.2 is the
version we are going to use in the release.

**Pull request closed without merging**
